version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sampletok_postgres
    environment:
      POSTGRES_USER: sampletok
      POSTGRES_PASSWORD: sampletok
      POSTGRES_DB: sampletok
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sampletok"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: sampletok_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/sampletok-samples --ignore-existing;
      /usr/bin/mc anonymous set public myminio/sampletok-samples;
      exit 0;
      "

volumes:
  postgres_data:
  minio_data: