#!/bin/bash

echo "🔧 Stripe CLI Setup for Local Development"
echo "=========================================="
echo ""

# Check if Stripe CLI is installed
if ! command -v stripe &> /dev/null; then
    echo "❌ Stripe CLI not found. Install it first:"
    echo "   brew install stripe/stripe-cli/stripe"
    exit 1
fi

echo "✅ Stripe CLI found: $(stripe --version)"
echo ""

# Step 1: Login
echo "📝 Step 1: Login to Stripe"
echo "----------------------------------------"
echo "Run this command to login (it will open your browser):"
echo ""
echo "  stripe login"
echo ""
read -p "Press Enter after you've logged in..."
echo ""

# Step 2: Get your test API keys
echo "📝 Step 2: Get Your Test API Keys"
echo "----------------------------------------"
echo "1. Open: https://dashboard.stripe.com/test/apikeys"
echo "2. Copy your 'Secret key' (starts with sk_test_)"
echo "3. Copy your 'Publishable key' (starts with pk_test_)"
echo ""
read -p "Press Enter when you have your keys..."
echo ""

# Step 3: Start webhook forwarding
echo "📝 Step 3: Start Webhook Forwarding"
echo "----------------------------------------"
echo "This will forward Stripe webhooks to your local backend."
echo "Keep this running in a separate terminal window!"
echo ""
echo "Run this command:"
echo ""
echo "  stripe listen --forward-to localhost:8000/api/v1/webhooks/stripe"
echo ""
echo "It will output a webhook signing secret (whsec_...)"
echo "Copy that secret - you'll need it for .env"
echo ""
read -p "Press Enter to continue..."
echo ""

# Step 4: Create products
echo "📝 Step 4: Create Products in Stripe Dashboard"
echo "----------------------------------------"
echo "Open: https://dashboard.stripe.com/test/products"
echo ""
echo "Create these subscription products:"
echo ""
echo "1. Sampletok Basic Monthly"
echo "   - Price: \$9.99/month (recurring)"
echo "   - Metadata: tier=basic, monthly_credits=100"
echo ""
echo "2. Sampletok Basic Annual"
echo "   - Price: \$99.50/year (recurring)"
echo "   - Metadata: tier=basic, monthly_credits=100"
echo ""
echo "3. Sampletok Pro Monthly"
echo "   - Price: \$16.99/month (recurring)"
echo "   - Metadata: tier=pro, monthly_credits=400"
echo ""
echo "4. Sampletok Pro Annual"
echo "   - Price: \$169.22/year (recurring)"
echo "   - Metadata: tier=pro, monthly_credits=400"
echo ""
echo "5. Sampletok Ultimate Monthly"
echo "   - Price: \$49.99/month (recurring)"
echo "   - Metadata: tier=ultimate, monthly_credits=1500"
echo ""
echo "6. Sampletok Ultimate Annual"
echo "   - Price: \$497.90/year (recurring)"
echo "   - Metadata: tier=ultimate, monthly_credits=1500"
echo ""
echo "Create these one-time payment products:"
echo ""
echo "7. Credit Top-Up Small"
echo "   - Price: \$4.99 (one-time)"
echo "   - Metadata: package=small, credits=50"
echo ""
echo "8. Credit Top-Up Medium"
echo "   - Price: \$14.99 (one-time)"
echo "   - Metadata: package=medium, credits=200"
echo ""
echo "9. Credit Top-Up Large"
echo "   - Price: \$39.99 (one-time)"
echo "   - Metadata: package=large, credits=600"
echo ""
read -p "Press Enter when you've created all products..."
echo ""

# Step 5: Update .env
echo "📝 Step 5: Update backend/.env"
echo "----------------------------------------"
echo "Add these values to your backend/.env file:"
echo ""
echo "STRIPE_SECRET_KEY=sk_test_YOUR_KEY_HERE"
echo "STRIPE_PUBLISHABLE_KEY=pk_test_YOUR_KEY_HERE"
echo "STRIPE_WEBHOOK_SECRET=whsec_YOUR_WEBHOOK_SECRET_HERE"
echo ""
echo "STRIPE_PRICE_BASIC_MONTHLY=price_YOUR_PRICE_ID"
echo "STRIPE_PRICE_BASIC_ANNUAL=price_YOUR_PRICE_ID"
echo "STRIPE_PRICE_PRO_MONTHLY=price_YOUR_PRICE_ID"
echo "STRIPE_PRICE_PRO_ANNUAL=price_YOUR_PRICE_ID"
echo "STRIPE_PRICE_ULTIMATE_MONTHLY=price_YOUR_PRICE_ID"
echo "STRIPE_PRICE_ULTIMATE_ANNUAL=price_YOUR_PRICE_ID"
echo ""
echo "STRIPE_PRICE_TOPUP_SMALL=price_YOUR_PRICE_ID"
echo "STRIPE_PRICE_TOPUP_MEDIUM=price_YOUR_PRICE_ID"
echo "STRIPE_PRICE_TOPUP_LARGE=price_YOUR_PRICE_ID"
echo ""

# Step 6: Test
echo "📝 Step 6: Test Everything"
echo "----------------------------------------"
echo "1. Start your backend server (it should auto-reload)"
echo "2. Start frontend: cd frontend && npm run dev"
echo "3. In another terminal, keep running:"
echo "   stripe listen --forward-to localhost:8000/api/v1/webhooks/stripe"
echo "4. Go to http://localhost:3000/pricing"
echo "5. Click subscribe and use test card: 4242 4242 4242 4242"
echo ""
echo "✅ Setup complete! Check the webhook terminal for events."
