"""Add collections and collection_samples tables

Revision ID: 051dca230c02
Revises: 7071cb6b2c81
Create Date: 2025-10-27 17:58:18.307270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051dca230c02'
down_revision = '7071cb6b2c81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tiktok_collection_id', sa.String(), nullable=False),
    sa.Column('tiktok_username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_video_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='collectionstatus'), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_created_at'), 'collections', ['created_at'], unique=False)
    op.create_index(op.f('ix_collections_status'), 'collections', ['status'], unique=False)
    op.create_index(op.f('ix_collections_tiktok_collection_id'), 'collections', ['tiktok_collection_id'], unique=False)
    op.create_index(op.f('ix_collections_tiktok_username'), 'collections', ['tiktok_username'], unique=False)
    op.create_index('ix_collections_tiktok_username_collection_id', 'collections', ['tiktok_username', 'tiktok_collection_id'], unique=False)
    op.create_index('ix_collections_user_created', 'collections', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('collection_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_samples_collection_id'), 'collection_samples', ['collection_id'], unique=False)
    op.create_index('ix_collection_samples_position', 'collection_samples', ['collection_id', 'position'], unique=False)
    op.create_index(op.f('ix_collection_samples_sample_id'), 'collection_samples', ['sample_id'], unique=False)
    op.create_index('ix_collection_samples_unique', 'collection_samples', ['collection_id', 'sample_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_collection_samples_unique', table_name='collection_samples')
    op.drop_index(op.f('ix_collection_samples_sample_id'), table_name='collection_samples')
    op.drop_index('ix_collection_samples_position', table_name='collection_samples')
    op.drop_index(op.f('ix_collection_samples_collection_id'), table_name='collection_samples')
    op.drop_table('collection_samples')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_index('ix_collections_user_created', table_name='collections')
    op.drop_index('ix_collections_tiktok_username_collection_id', table_name='collections')
    op.drop_index(op.f('ix_collections_tiktok_username'), table_name='collections')
    op.drop_index(op.f('ix_collections_tiktok_collection_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_status'), table_name='collections')
    op.drop_index(op.f('ix_collections_created_at'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###