"""Add user downloads and favorites tracking

Revision ID: 0a85a61856eb
Revises: 387cfdfcb1a1
Create Date: 2025-10-25 15:53:19.843235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a85a61856eb'
down_revision = '387cfdfcb1a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_downloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('download_type', sa.String(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_downloads_user_date', 'user_downloads', ['user_id', 'downloaded_at'], unique=False)
    op.create_index('idx_user_downloads_user_sample', 'user_downloads', ['user_id', 'sample_id'], unique=False)
    op.create_table('user_favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('favorited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sample_id', name='uix_user_sample_favorite')
    )
    op.create_index('idx_user_favorites_user_date', 'user_favorites', ['user_id', 'favorited_at'], unique=False)
    op.drop_table('user_samples')
    op.add_column('samples', sa.Column('download_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'download_count')
    op.create_table('user_samples',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sample_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('downloaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], name=op.f('user_samples_sample_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_samples_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'sample_id', name=op.f('user_samples_pkey'))
    )
    op.drop_index('idx_user_favorites_user_date', table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index('idx_user_downloads_user_sample', table_name='user_downloads')
    op.drop_index('idx_user_downloads_user_date', table_name='user_downloads')
    op.drop_table('user_downloads')
    # ### end Alembic commands ###