"""Add user_stem_downloads table and stem download_count

Revision ID: 0d0e4575825d
Revises: fc13ea67ef28
Create Date: 2025-11-01 12:16:57.128593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0e4575825d'
down_revision = 'fc13ea67ef28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stem_downloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stem_id', sa.UUID(), nullable=False),
    sa.Column('download_type', sa.String(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stem_id'], ['stems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_stem_downloads_user_date', 'user_stem_downloads', ['user_id', 'downloaded_at'], unique=False)
    op.create_index('idx_user_stem_downloads_user_stem', 'user_stem_downloads', ['user_id', 'stem_id'], unique=False)
    op.add_column('stems', sa.Column('download_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stems', 'download_count')
    op.drop_index('idx_user_stem_downloads_user_stem', table_name='user_stem_downloads')
    op.drop_index('idx_user_stem_downloads_user_date', table_name='user_stem_downloads')
    op.drop_table('user_stem_downloads')
    # ### end Alembic commands ###