"""Add Clerk authentication support to User model

Revision ID: 387cfdfcb1a1
Revises: f7ed94abf848
Create Date: 2025-10-25 13:50:29.739516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387cfdfcb1a1'
down_revision = 'f7ed94abf848'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_user_id', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'clerk_user_id')
    # ### end Alembic commands ###