"""Add sample_dismissals table for mobile feed

Revision ID: 4be5e02bf74e
Revises: e6a6eaec41cf
Create Date: 2025-11-09 14:58:57.074850

Creates sample_dismissals table to track user-dismissed samples
for personalized mobile feed. Enables:
- Tinder-style swipe dismiss functionality
- Personalized feed excluding dismissed samples
- Guest data sync after login

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be5e02bf74e'
down_revision = 'e6a6eaec41cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_dismissals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sample_id', name='uix_user_sample_dismissal')
    )
    op.create_index('idx_sample_dismissals_user_date', 'sample_dismissals', ['user_id', 'dismissed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sample_dismissals_user_date', table_name='sample_dismissals')
    op.drop_table('sample_dismissals')
    # ### end Alembic commands ###