"""Add pagination fields to collections

Revision ID: 56ccaf09acd1
Revises: 051dca230c02
Create Date: 2025-10-27 18:11:05.145145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ccaf09acd1'
down_revision = '051dca230c02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('current_cursor', sa.Integer(), nullable=False))
    op.add_column('collections', sa.Column('next_cursor', sa.Integer(), nullable=True))
    op.add_column('collections', sa.Column('has_more', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'has_more')
    op.drop_column('collections', 'next_cursor')
    op.drop_column('collections', 'current_cursor')
    # ### end Alembic commands ###