"""Initial migration with users and samples tables

Revision ID: 7ab896202ecc
Revises: 
Create Date: 2025-09-20 17:51:20.781848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ab896202ecc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tiktok_url', sa.String(), nullable=False),
    sa.Column('tiktok_id', sa.String(), nullable=True),
    sa.Column('creator_username', sa.String(), nullable=True),
    sa.Column('creator_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audio_url_wav', sa.String(), nullable=True),
    sa.Column('audio_url_mp3', sa.String(), nullable=True),
    sa.Column('waveform_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('file_size_wav', sa.Integer(), nullable=True),
    sa.Column('file_size_mp3', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_created_at'), 'samples', ['created_at'], unique=False)
    op.create_index(op.f('ix_samples_creator_username'), 'samples', ['creator_username'], unique=False)
    op.create_index(op.f('ix_samples_tiktok_id'), 'samples', ['tiktok_id'], unique=True)
    op.create_index(op.f('ix_samples_tiktok_url'), 'samples', ['tiktok_url'], unique=False)
    op.create_table('user_samples',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'sample_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_samples')
    op.drop_index(op.f('ix_samples_tiktok_url'), table_name='samples')
    op.drop_index(op.f('ix_samples_tiktok_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_creator_username'), table_name='samples')
    op.drop_index(op.f('ix_samples_created_at'), table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###