"""Add instagram_engagements table for mention tracking

Revision ID: 83ea67650baa
Revises: 4be5e02bf74e
Create Date: 2025-11-19 06:56:28.281982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83ea67650baa'
down_revision = '4be5e02bf74e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_engagements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instagram_media_id', sa.String(), nullable=False),
    sa.Column('instagram_shortcode', sa.String(), nullable=True),
    sa.Column('instagram_permalink', sa.String(), nullable=True),
    sa.Column('engagement_type', sa.Enum('MENTION', 'COMMENT', 'STORY_MENTION', name='engagementtype'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'SKIPPED', name='engagementstatus'), nullable=True),
    sa.Column('instagram_user_id', sa.String(), nullable=True),
    sa.Column('instagram_username', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.UUID(), nullable=True),
    sa.Column('comment_id', sa.String(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('comment_posted_at', sa.DateTime(), nullable=True),
    sa.Column('webhook_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_engagements_created_at'), 'instagram_engagements', ['created_at'], unique=False)
    op.create_index(op.f('ix_instagram_engagements_detected_at'), 'instagram_engagements', ['detected_at'], unique=False)
    op.create_index(op.f('ix_instagram_engagements_engagement_type'), 'instagram_engagements', ['engagement_type'], unique=False)
    op.create_index(op.f('ix_instagram_engagements_instagram_media_id'), 'instagram_engagements', ['instagram_media_id'], unique=True)
    op.create_index(op.f('ix_instagram_engagements_instagram_shortcode'), 'instagram_engagements', ['instagram_shortcode'], unique=False)
    op.create_index(op.f('ix_instagram_engagements_instagram_user_id'), 'instagram_engagements', ['instagram_user_id'], unique=False)
    op.create_index(op.f('ix_instagram_engagements_instagram_username'), 'instagram_engagements', ['instagram_username'], unique=False)
    op.create_index(op.f('ix_instagram_engagements_sample_id'), 'instagram_engagements', ['sample_id'], unique=False)
    op.create_index(op.f('ix_instagram_engagements_status'), 'instagram_engagements', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instagram_engagements_status'), table_name='instagram_engagements')
    op.drop_index(op.f('ix_instagram_engagements_sample_id'), table_name='instagram_engagements')
    op.drop_index(op.f('ix_instagram_engagements_instagram_username'), table_name='instagram_engagements')
    op.drop_index(op.f('ix_instagram_engagements_instagram_user_id'), table_name='instagram_engagements')
    op.drop_index(op.f('ix_instagram_engagements_instagram_shortcode'), table_name='instagram_engagements')
    op.drop_index(op.f('ix_instagram_engagements_instagram_media_id'), table_name='instagram_engagements')
    op.drop_index(op.f('ix_instagram_engagements_engagement_type'), table_name='instagram_engagements')
    op.drop_index(op.f('ix_instagram_engagements_detected_at'), table_name='instagram_engagements')
    op.drop_index(op.f('ix_instagram_engagements_created_at'), table_name='instagram_engagements')
    op.drop_table('instagram_engagements')

    # Drop the ENUM types (Alembic doesn't auto-generate this)
    sa.Enum(name='engagementtype').drop(op.get_bind())
    sa.Enum(name='engagementstatus').drop(op.get_bind())
    # ### end Alembic commands ###