"""Add HLS playlist URL to samples

Revision ID: 8577e3e22893
Revises: 99b73b59c5c0
Create Date: 2025-11-01 15:01:35.787166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8577e3e22893'
down_revision = '99b73b59c5c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('audio_url_hls', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'audio_url_hls')
    # ### end Alembic commands ###