"""add instagram support

Revision ID: 87f97ad25b2c
Revises: 1e2511774164
Create Date: 2025-11-07 17:36:31.080215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f97ad25b2c'
down_revision = '1e2511774164'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first
    samplesource_enum = sa.Enum('TIKTOK', 'INSTAGRAM', name='samplesource')
    samplesource_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('instagram_creators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instagram_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('profile_pic_url', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_creators_created_at'), 'instagram_creators', ['created_at'], unique=False)
    op.create_index(op.f('ix_instagram_creators_instagram_id'), 'instagram_creators', ['instagram_id'], unique=True)
    op.create_index(op.f('ix_instagram_creators_username'), 'instagram_creators', ['username'], unique=True)
    op.add_column('samples', sa.Column('source', samplesource_enum, nullable=True))
    op.add_column('samples', sa.Column('instagram_url', sa.String(), nullable=True))
    op.add_column('samples', sa.Column('instagram_id', sa.String(), nullable=True))
    op.add_column('samples', sa.Column('instagram_shortcode', sa.String(), nullable=True))
    op.add_column('samples', sa.Column('instagram_creator_id', sa.UUID(), nullable=True))
    op.alter_column('samples', 'tiktok_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_samples_bpm'), table_name='samples')
    op.drop_index(op.f('ix_samples_key'), table_name='samples')
    op.drop_index(op.f('ix_samples_tags_gin'), table_name='samples', postgresql_using='gin')
    op.create_index(op.f('ix_samples_instagram_id'), 'samples', ['instagram_id'], unique=True)
    op.create_index(op.f('ix_samples_instagram_shortcode'), 'samples', ['instagram_shortcode'], unique=True)
    op.create_index(op.f('ix_samples_instagram_url'), 'samples', ['instagram_url'], unique=False)
    op.create_index(op.f('ix_samples_source'), 'samples', ['source'], unique=False)
    op.create_foreign_key(None, 'samples', 'instagram_creators', ['instagram_creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.drop_index(op.f('ix_samples_source'), table_name='samples')
    op.drop_index(op.f('ix_samples_instagram_url'), table_name='samples')
    op.drop_index(op.f('ix_samples_instagram_shortcode'), table_name='samples')
    op.drop_index(op.f('ix_samples_instagram_id'), table_name='samples')
    op.create_index(op.f('ix_samples_tags_gin'), 'samples', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_samples_key'), 'samples', ['key'], unique=False)
    op.create_index(op.f('ix_samples_bpm'), 'samples', ['bpm'], unique=False)
    op.alter_column('samples', 'tiktok_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('samples', 'instagram_creator_id')
    op.drop_column('samples', 'instagram_shortcode')
    op.drop_column('samples', 'instagram_id')
    op.drop_column('samples', 'instagram_url')
    op.drop_column('samples', 'source')
    op.drop_index(op.f('ix_instagram_creators_username'), table_name='instagram_creators')
    op.drop_index(op.f('ix_instagram_creators_instagram_id'), table_name='instagram_creators')
    op.drop_index(op.f('ix_instagram_creators_created_at'), table_name='instagram_creators')
    op.drop_table('instagram_creators')

    # Drop the ENUM type
    samplesource_enum = sa.Enum('TIKTOK', 'INSTAGRAM', name='samplesource')
    samplesource_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###