"""Add stem_id to credit_transactions

Revision ID: 99b73b59c5c0
Revises: 0d0e4575825d
Create Date: 2025-11-01 13:18:55.961555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b73b59c5c0'
down_revision = '0d0e4575825d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transactions', sa.Column('stem_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'credit_transactions', 'stems', ['stem_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credit_transactions', type_='foreignkey')
    op.drop_column('credit_transactions', 'stem_id')
    # ### end Alembic commands ###