"""Make instagram_engagement sample_id nullable

Revision ID: 9ca38fdd096e
Revises: 4c48afe435d7
Create Date: 2025-11-19 11:58:55.951605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca38fdd096e'
down_revision = '4c48afe435d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instagram_engagements', 'sample_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instagram_engagements', 'sample_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###