"""Add stems table for stem separation

Revision ID: b7b66599d05e
Revises: 7459cff6a67f
Create Date: 2025-11-01 10:07:26.388175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b66599d05e'
down_revision = '7459cff6a67f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_sample_id', sa.UUID(), nullable=False),
    sa.Column('stem_type', sa.Enum('VOCAL', 'VOICE', 'DRUM', 'PIANO', 'BASS', 'ELECTRIC_GUITAR', 'ACOUSTIC_GUITAR', 'SYNTHESIZER', 'STRINGS', 'WIND', name='stemtype'), nullable=False),
    sa.Column('file_path_wav', sa.String(), nullable=True),
    sa.Column('file_path_mp3', sa.String(), nullable=True),
    sa.Column('audio_url_wav', sa.String(), nullable=True),
    sa.Column('audio_url_mp3', sa.String(), nullable=True),
    sa.Column('file_size_wav', sa.Integer(), nullable=True),
    sa.Column('file_size_mp3', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADING', 'PROCESSING', 'DOWNLOADING', 'ANALYZING', 'COMPLETED', 'FAILED', name='stemprocessingstatus'), nullable=False),
    sa.Column('lalal_task_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stems_created_at'), 'stems', ['created_at'], unique=False)
    op.create_index(op.f('ix_stems_parent_sample_id'), 'stems', ['parent_sample_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stems_parent_sample_id'), table_name='stems')
    op.drop_index(op.f('ix_stems_created_at'), table_name='stems')
    op.drop_table('stems')
    # ### end Alembic commands ###