"""Add check constraint to prevent negative credits

Revision ID: ca613d944f79
Revises: 56ccaf09acd1
Create Date: 2025-10-28 16:09:59.571802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca613d944f79'
down_revision = '56ccaf09acd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        'check_credits_non_negative',
        'users',
        'credits >= 0'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_credits_non_negative', 'users', type_='check')
    # ### end Alembic commands ###