"""add follower counts to instagram creators

Revision ID: e6a6eaec41cf
Revises: 87f97ad25b2c
Create Date: 2025-11-08 14:18:35.603611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a6eaec41cf'
down_revision = '87f97ad25b2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_creators', sa.Column('follower_count', sa.Integer(), nullable=True))
    op.add_column('instagram_creators', sa.Column('following_count', sa.Integer(), nullable=True))
    op.add_column('instagram_creators', sa.Column('media_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_creators', 'media_count')
    op.drop_column('instagram_creators', 'following_count')
    op.drop_column('instagram_creators', 'follower_count')
    # ### end Alembic commands ###