"""add user_stem_favorites table

Revision ID: fc13ea67ef28
Revises: b7b66599d05e
Create Date: 2025-11-01 11:54:10.124479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc13ea67ef28'
down_revision = 'b7b66599d05e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stem_favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stem_id', sa.UUID(), nullable=False),
    sa.Column('favorited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stem_id'], ['stems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stem_id', name='uix_user_stem_favorite')
    )
    op.create_index('idx_user_stem_favorites_user_date', 'user_stem_favorites', ['user_id', 'favorited_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_stem_favorites_user_date', table_name='user_stem_favorites')
    op.drop_table('user_stem_favorites')
    # ### end Alembic commands ###